name: termshark
version: '2.3.0'
summary: A terminal UI for tshark, inspired by Wireshark 
description: |
  A terminal UI for tshark, inspired by Wireshark.

confinement: strict
grade: stable
base: core18

parts:
  termshark:
    plugin: go
    source: https://github.com/gcla/termshark.git
    source-type: git
    build-environment:
      - GO111MODULE: 'on'
      - CGO_ENABLED: '0'
      - GOROOT: '/usr/local/go'
    override-pull: |
        echo "Skipping pull stage."
    override-build: |
        mkdir $SNAPCRAFT_PART_INSTALL/bin
        export GOBIN=$SNAPCRAFT_PART_INSTALL/bin
        apt-get install wget
        wget https://golang.org/dl/go1.17.linux-amd64.tar.gz
        tar xvf go1.17.linux-amd64.tar.gz
        mv go /usr/local/
        git clone https://github.com/gcla/termshark.git
        cd termshark
        git checkout v2.3.0
        /usr/local/go/bin/go install ./...
    build-packages:
      - gcc
    stage-packages:
      - tshark

apps:
  termshark:
    command: bin/termshark
    plugs:
      - network
      - network-control
      - ppp
      - bluetooth-control
      - raw-usb
      - home
      - firewall-control
      - removable-media
